# Generated by Django 4.0.4 on 2022-05-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10, verbose_name='商品分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=10, verbose_name='颜色名称')),
                ('colorurl', models.ImageField(upload_to='color/', verbose_name='颜色保存路径')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100, verbose_name='商品名称')),
                ('gdesc', models.CharField(max_length=100, verbose_name='商品描述')),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品原价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品现价')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetailName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdname', models.CharField(max_length=30, verbose_name='商品详细名称')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10, verbose_name='商品尺寸名称')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(verbose_name='库存数量')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.color', verbose_name='所属颜色')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods', verbose_name='所属商品')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.size', verbose_name='所数尺寸')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdurl', models.ImageField(upload_to='', verbose_name='详细图片路径')),
                ('detailname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goodsdetailname', verbose_name='商品详细名称')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods')),
            ],
        ),
    ]
