# Generated by Django 4.0.4 on 2022-06-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.PositiveIntegerField(verbose_name='商品id')),
                ('colorid', models.PositiveIntegerField(verbose_name='颜色id')),
                ('sizeid', models.PositiveIntegerField(verbose_name='尺寸id')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='商品数量')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo', verbose_name='用户')),
            ],
        ),
    ]
